<a href="https://colab.research.google.com/github/Ashishpathak78/ML_-Practice/blob/Ashish/23_07_25_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Creating the original Sales DataFrame
data = {
    2014: [100.5, 150.8, 200.9, 30000, 40000],
    2015: [12000, 18000, 22000, 30000, 45000],
    2016: [20000, 50000, 70000, 100000, 125000],
    2017: [50000, 60000, 70000, 80000, 90000]
}
index = ['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti']
Sales = pd.DataFrame(data, index=index)


In [ ]:
print("Row labels (index):", Sales.index.tolist())


Row labels (index): ['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti']


In [ ]:
print("Column labels:", Sales.columns.tolist())


Column labels: [2014, 2015, 2016, 2017]


In [ ]:
print("Data types:\n", Sales.dtypes)


Data types:
 2014    float64
2015      int64
2016      int64
2017      int64
dtype: object


In [ ]:
print("Dimensions (ndim):", Sales.ndim)
print("Shape (rows, columns):", Sales.shape)
print("Size (total elements):", Sales.size)
print("Values (as numpy array):\n", Sales.values)


Dimensions (ndim): 2
Shape (rows, columns): (5, 4)
Size (total elements): 20
Values (as numpy array):
 [[1.005e+02 1.200e+04 2.000e+04 5.000e+04]
 [1.508e+02 1.800e+04 5.000e+04 6.000e+04]
 [2.009e+02 2.200e+04 7.000e+04 7.000e+04]
 [3.000e+04 3.000e+04 1.000e+05 8.000e+04]
 [4.000e+04 4.500e+04 1.250e+05 9.000e+04]]


In [ ]:
print("Last two rows:\n", Sales.tail(2))


Last two rows:
            2014   2015    2016   2017
Ankit   30000.0  30000  100000  80000
Shruti  40000.0  45000  125000  90000


In [ ]:
print("First two columns:\n", Sales.iloc[:, :2])


First two columns:
             2014   2015
Madhu      100.5  12000
Kusum      150.8  18000
Kinshuk    200.9  22000
Ankit    30000.0  30000
Shruti   40000.0  45000


In [ ]:
sales_data_2018 = {
    'Madhu': 160000,
    'Kusum': 110000,
    'Kinshuk': 500000,
    'Ankit': 340000,
    'Shruti': 900000
}
Sales2 = pd.DataFrame.from_dict(sales_data_2018, orient='index', columns=[2018])
print("Sales2 DataFrame:\n", Sales2)


Sales2 DataFrame:
            2018
Madhu    160000
Kusum    110000
Kinshuk  500000
Ankit    340000
Shruti   900000


In [ ]:
if Sales2.empty:
    print("Sales2 is empty.")
else:
    print("Sales2 contains data.")


Sales2 contains data.


In [ ]:
Sales = pd.concat([Sales, Sales2], axis=1)
print(Sales)


            2014   2015    2016   2017    2018
Madhu      100.5  12000   20000  50000  160000
Kusum      150.8  18000   50000  60000  110000
Kinshuk    200.9  22000   70000  70000  500000
Ankit    30000.0  30000  100000  80000  340000
Shruti   40000.0  45000  125000  90000  900000


In [ ]:
Sales = Sales.T
print(Sales)


         Madhu     Kusum   Kinshuk     Ankit    Shruti
2014     100.5     150.8     200.9   30000.0   40000.0
2015   12000.0   18000.0   22000.0   30000.0   45000.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0


In [ ]:
print("Sales in 2017:\n", Sales.loc[2017])
print(Sales.iloc[3])

Sales in 2017:
 Madhu      50000.0
Kusum      60000.0
Kinshuk    70000.0
Ankit      80000.0
Shruti     90000.0
Name: 2017, dtype: float64
Madhu      50000.0
Kusum      60000.0
Kinshuk    70000.0
Ankit      80000.0
Shruti     90000.0
Name: 2017, dtype: float64


In [ ]:
print("Madhu & Ankit sales in 2017 & 2018:\n", Sales.loc[[2017, 2018], ['Madhu', 'Ankit']])


Madhu & Ankit sales in 2017 & 2018:
          Madhu     Ankit
2017   50000.0   80000.0
2018  160000.0  340000.0


In [ ]:
print("Shruti's sales in 2016:", Sales.at[2016, 'Shruti'])

Shruti's sales in 2016: 125000.0


In [ ]:
Sales['Sumeet'] = [196.2, 37800, 52000, 78438, 38852]  # Add as new column
print("After adding Sumeet:\n", Sales)


After adding Sumeet:
          Madhu     Kusum   Kinshuk     Ankit    Shruti   Sumeet
2014     100.5     150.8     200.9   30000.0   40000.0    196.2
2015   12000.0   18000.0   22000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0  38852.0


In [ ]:
Sales = Sales.drop(2014)
print("After dropping 2014:\n", Sales)


After dropping 2014:
          Madhu     Kusum   Kinshuk     Ankit    Shruti   Sumeet
2015   12000.0   18000.0   22000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0  38852.0


In [ ]:
Sales = Sales.drop(columns='Kinshuk')
print("After dropping Kinshuk:\n", Sales)


After dropping Kinshuk:
          Madhu     Kusum     Ankit    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0  38852.0


In [ ]:
Sales = Sales.rename(columns={'Ankit': 'Vivaan', 'Madhu': 'Shailesh'})
print("After renaming:\n", Sales)


After renaming:
       Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0  38852.0


In [ ]:
Sales.at[2018, 'Shailesh'] = 100000
print("After updating Shailesh's 2018 sale:\n", Sales)


After updating Shailesh's 2018 sale:
       Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  100000.0  110000.0  340000.0  900000.0  38852.0


In [ ]:
Sales.to_csv("SalesFigures.csv", index=False, header=False)
print("Data written to SalesFigures.csv (no headers or index).")


Data written to SalesFigures.csv (no headers or index).


In [ ]:
SalesRetrieved = pd.read_csv("SalesFigures.csv", header=None)

# Update column and row labels to match `Sales`
SalesRetrieved.columns = Sales.columns
SalesRetrieved.index = Sales.index

print("SalesRetrieved DataFrame:\n", SalesRetrieved)


SalesRetrieved DataFrame:
       Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  100000.0  110000.0  340000.0  900000.0  38852.0


In [ ]:
import pandas as pd

# Define the data
data = {
    'Item': ['TV', 'TV', 'TV', 'AC'],
    'Company': ['LG', 'VIDEOCON', 'LG', 'SONY'],
    'Rupees': [12000, 10000, 15000, 14000],
    'USD': [700, 650, 800, 750]
}

# Create the DataFrame
Product = pd.DataFrame(data)
print("Product DataFrame:\n", Product)


Product DataFrame:
   Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750


In [ ]:
new_rows = pd.DataFrame([
    {'Item': 'AC', 'Company': 'LG', 'Rupees': 20000, 'USD': 900},
    {'Item': 'TV', 'Company': 'SONY', 'Rupees': 13000, 'USD': 720}
])

# Append new rows to original DataFrame
Product = pd.concat([Product, new_rows], ignore_index=True)
print("Updated Product DataFrame:\n", Product)


Updated Product DataFrame:
   Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750
4   AC        LG   20000  900
5   TV      SONY   13000  720


In [ ]:
max_price = Product[(Product['Company'] == 'LG') & (Product['Item'] == 'TV')]['Rupees'].max()
print("Maximum price of LG TV:", max_price)


Maximum price of LG TV: 15000


In [ ]:
total_sum = Product['Rupees'].sum()
print("Total sum of all products in Rupees:", total_sum)


Total sum of all products in Rupees: 84000


In [ ]:
median_usd_sony = Product[Product['Company'] == 'SONY']['USD'].median()
print("Median USD of SONY products:", median_usd_sony)


Median USD of SONY products: 735.0


In [ ]:
sorted_product = Product.sort_values(by='Rupees')
print("Sorted DataFrame:\n", sorted_product)


Sorted DataFrame:
   Item   Company  Rupees  USD
1   TV  VIDEOCON   10000  650
0   TV        LG   12000  700
5   TV      SONY   13000  720
3   AC      SONY   14000  750
2   TV        LG   15000  800
4   AC        LG   20000  900


In [ ]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Aparna', 'Pankaj', 'Ram', 'Ramesh', 'Naveen', 'Krrishav', 'Bhawna'],
    'Degree': ['MBA', 'BCA', 'M.Tech', 'MBA', np.nan, 'BCA', 'MBA'],
    'Score': [90.0, np.nan, 80.0, 98.0, 97.0, 78.0, 89.0]
}

df = pd.DataFrame(data)
print(df)


       Name  Degree  Score
0    Aparna     MBA   90.0
1    Pankaj     BCA    NaN
2       Ram  M.Tech   80.0
3    Ramesh     MBA   98.0
4    Naveen     NaN   97.0
5  Krrishav     BCA   78.0
6    Bhawna     MBA   89.0


In [ ]:
print(df.groupby('Degree')['Score'].max())


Degree
BCA       78.0
M.Tech    80.0
MBA       98.0
Name: Score, dtype: float64


In [ ]:
df_filled = df.fillna(76)
print(df_filled)


       Name  Degree  Score
0    Aparna     MBA   90.0
1    Pankaj     BCA   76.0
2       Ram  M.Tech   80.0
3    Ramesh     MBA   98.0
4    Naveen      76   97.0
5  Krrishav     BCA   78.0
6    Bhawna     MBA   89.0


In [ ]:
df_indexed = df.set_index('Name')
print(df_indexed)


          Degree  Score
Name                   
Aparna       MBA   90.0
Pankaj       BCA    NaN
Ram       M.Tech   80.0
Ramesh       MBA   98.0
Naveen       NaN   97.0
Krrishav     BCA   78.0
Bhawna       MBA   89.0


In [ ]:
print(df.groupby(['Name', 'Degree'])['Score'].mean())


Name      Degree
Aparna    MBA       90.0
Bhawna    MBA       89.0
Krrishav  BCA       78.0
Pankaj    BCA        NaN
Ram       M.Tech    80.0
Ramesh    MBA       98.0
Name: Score, dtype: float64


In [ ]:
mba_count = df[df['Degree'] == 'MBA'].shape[0]
print("Number of MBA students:", mba_count)


Number of MBA students: 3


In [ ]:
bca_mode = df[df['Degree'] == 'BCA']['Score'].mode()
print("Mode marks in BCA:\n", bca_mode)



Mode marks in BCA:
 0    78.0
Name: Score, dtype: float64
